# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newReportDialog(object):
    def setupUi(self, newReportDialog):
        self.newReportDialog = newReportDialog
        self.newReportDialog.setObjectName("newReportDialog")
        self.newReportDialog.resize(246, 236)
        self.buttonBox = QtWidgets.QDialogButtonBox(newReportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-120, 180, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelMonth = QtWidgets.QLabel(newReportDialog)
        self.labelMonth.setGeometry(QtCore.QRect(30, 20, 55, 21))
        self.labelMonth.setObjectName("labelMonth")
        self.comboMonthInput = QtWidgets.QComboBox(newReportDialog)
        self.comboMonthInput.setGeometry(QtCore.QRect(80, 20, 111, 22))
        self.comboMonthInput.setObjectName("comboMonthInput")
        self.labelYearI = QtWidgets.QLabel(newReportDialog)
        self.labelYearI.setGeometry(QtCore.QRect(20, 60, 55, 21))
        self.labelYearI.setObjectName("labelYearI")
        self.yearInput = QtWidgets.QSpinBox(newReportDialog)
        self.yearInput.setGeometry(QtCore.QRect(80, 60, 71, 22))
        self.yearInput.setMaximum(9999)
        self.yearInput.setObjectName("yearInput")
        self.groupBox = QtWidgets.QGroupBox(newReportDialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 100, 161, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioBtnDXA = QtWidgets.QRadioButton(self.groupBox)
        self.radioBtnDXA.setGeometry(QtCore.QRect(90, 30, 121, 20))
        self.radioBtnDXA.setObjectName("radioBtnDXA")
        self.radioBtnDXA.setChecked(True)
        self.radioBtnABPM = QtWidgets.QRadioButton(self.groupBox)
        self.radioBtnABPM.setEnabled(True)
        self.radioBtnABPM.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.radioBtnABPM.setObjectName("radioBtnABPM")

        self.retranslateUi(newReportDialog)
        self.buttonBox.accepted.connect(newReportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(newReportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(newReportDialog)

    def retranslateUi(self, newReportDialog):
        _translate = QtCore.QCoreApplication.translate
        newReportDialog.setWindowTitle(_translate("newReportDialog", "Novi Izvestaj"))
        self.labelMonth.setText(_translate("newReportDialog", "Mesec:"))
        self.labelYearI.setText(_translate("newReportDialog", "Godina:"))
        self.groupBox.setTitle(_translate("newReportDialog", "Tip:"))
        self.radioBtnDXA.setText(_translate("newReportDialog", "DXA"))
        self.radioBtnABPM.setText(_translate("newReportDialog", "ABPM"))
